spring.application.name=eagle
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
# username & password would be stored in a more secure location in real system (ie. Vault/secure DB)
spring.datasource.username=sa 
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

auth.jwt.username=admin
auth.jwt.password=password
auth.jwt.signingKey=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#default timeout of 30 mins
auth.jwt.timeout=1800000